### ISSUE TITLE
Create Simple-ML stub files

### ISSUE THREAD

**Issue by lars-reimann** [lars-reimann/api-editor#292]
### Is your feature request related to a problem? Please describe

In addition to the Python files that are generated in #288, Simple-ML stub files should be generated.

### Stub files syntax

```
package simpleml.model.regression

import simpleml.dataset.Dataset
import simpleml.model.Estimator

open class Lasso constructor(regularizationStrength: Float or 0.5) sub Estimator {
    attr regularizationStrength: Float

    override fun fit(features: Dataset, target: Dataset) -> trainedModel: TrainedLasso
}

fun println(obj: Any)
```

Let's go through this step by step:

```
package simpleml.model.regression
```

Package declaration as in Java. Corresponds to a Python file `simpleml/model/regression.py`.

----------------------

```
import simpleml.dataset.Dataset
import simpleml.model.Estimator
```

Imports like in Java. First we import a declaration called `Dataset` from the `simpleml.dataset` package then a declaration called `Estimator` from `simpleml.model`.

----------------------

```
open class Lasso
```

Declares that a class called `Lasso` exists in this package (`simpleml.model.regression`) and that it is open for extension. Opposite to Java classes are `final` by default and need to be marked explicitly as open so other classes can inherit from them.

----------------------

```
constructor(regularizationStrength: Float or 0.5)
```

The class has a constructor (`__init__` function in Python) that take on parameter called `regularizationStrength` of type `Float` and has a default value of `0.5`. The `self` parameter from Python must not be added and is implicitly assumed.

----------------------

```
sub Estimator
```

The class is a subclass of `Estimator`.

----------------------

```
attr regularizationStrength: Float
```

The class has an attribute (instance variable) called `regularizationStrength` with type `Float`.

----------------------

```
override fun fit(features: Dataset, target: Dataset) -> trainedModel: TrainedLasso
```

The class overrides the function called `fit` it inherits from `Estimator`. It takes two parameters called `features` and `target`, both of which have type `Dataset` and produces one result called `trainedModel` that has type `TrainedLasso`.

----------------------

```
fun println(obj: Any?)
```

A global function called `println` that takes one parameter that is an instance of any type or `null` (indicated by the question mark). `null` corresponds to `None` in Python and the question mark to [`Optional`](https://docs.python.org/3/library/typing.html#typing.Optional).

### Limitations

Not all the information specified above is available yet. Here's a list of possible problems and their resolution:
* Datatypes might not be known. In that case use `Any?` as the type.
* Imports can be challenging since we need the qualified name of the datatypes.
* Subclassing is challenging (`open`, `sub`, `override`). In a first iteration we may ignore subclassing and omit all this information. The work necessary to implement this is tracked separately in #293.
* Attributes are not currently known. However, in scikit-learn all parameters of a constructor are also available as attributes on the class under the same name.

### Tasks

- [x] Package declaration
- [x] Class declaration
- [x] Constructors of classes
- [x] Attributes of classes
- [x] Methods of classes
- [x] Global functions
