### ISSUE TITLE
Improve server model

### ISSUE THREAD

**Issue by lars-reimann** [lars-reimann/api-editor#338]
### Is your feature request related to a problem? Please describe

The server model has a few shortcomings.

### Tasks

- [x] Infer the name from the qualified name or vice versa.
- [ ] Store imports needed for typing and imports needed for calls separately. Only the type-related imports should appear in stubs.
- [x] Represent calls (qualified name of called function + arguments); must also work for enums/parameter objects; then parameters no longer need a link to the original declaration
- [x] Represent arguments (expression + optional name)
- [x] Represent references (e.g. to parameter)
- [x] Represent values/literals (string, int etc.). Useful for calls and default values.
- [ ] Represent constraints (e.g. boundary) -> create an `if` + `raise` in codegen; also rename boundary to constraints
