### ISSUE TITLE
`@Todo` annotation

### ISSUE THREAD

**Issue by lars-reimann** [lars-reimann/api-editor#515]
### Is your feature request related to a problem? Please describe

Currently there is no way to take notes about
* updates that have to be done manually
* annotation that might be added later.

### Desired solution

Add a `@Todo` annotation that
* is applicable to classes and functions (**not** parameters!)
* can be used once
* takes an arbitrary, potentially long text as input

In the generated Python code [`TODO` comments](https://stackoverflow.com/questions/48645942/how-do-i-format-a-multi-line-todo-comment-in-pycharm) with the text of the annotation should be added.

**Comment by lars-reimann** [comment]
The branch `515-todo-annotation` already contains the required changes to the backend.

**Comment by Masara** [comment]
Ähnlich wi bei der DescriptionAnnotation:

### Summary of Changes

In `src/features/annotations/annotationSlice.ts`:
- [x] Add interface for `DescriptionAnnotation`
- [x] Update `AnnotationStore`
- [x] Update `initialState`
- [x] Add `upsertDescriptionAnnotation`/`removeDescriptionAnnotation` reducers to `annotationsSlice`
- [x] Export these two reducers
- [x] Add and export `selectDescriptionAnnotation` selector

In `src/features/ui/uiSlice.ts`:
- [x] Add interface for `DescriptionUserAction`
- [x] Update `UserAction`

Other:
- [x] Update `src/features/annotations/AnnotationDropdown.tsx` (sort entries alphabetically)
- [x] Update all places that use the `AnnotationDropdown`
- [x] Update `src/features/annotations/AnnotationImportDialog.tsx`; might replace the object in line 25 with the `initialState` from `src/features/annotations/annotationSlice.ts`, so we don't need to update this in the future
- [x] Update `src/features/annotations/AnnotationView.tsx`
- [x] Add form in `src/features/annotations/forms`
- [x] Update `src/app/App.tsx` to show form when corresponding user action is active
- [x] Add filter `annotation:@description` (`src/features/packageData/model/filters/filterFactory.ts` and `src/features/packageData/model/filters/AnnotationFilter.ts`)
- [x] Update filter help text (`src/common/FilterHelpButton.tsx`)
- [x] Update `src/features/annotatedPackageData/model/InferableAnnotation.ts`
- [x] Update computation of number of annotations per element throughout the program (currently only heat map tags, later also #534)

### Screenshots (if necessary)



### Testing Instructions
