### ISSUE TITLE
ESLint not working

### ISSUE THREAD

**Issue by lars-reimann** [lars-reimann/api-editor#543]
### Describe the bug

ESLint is seemingly not properly configured anymore since the repo merge.

### Tasks

- [x] Move ESLint config files to top of repository
- [x] Update config to [disallow default exports](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-default-export.md). Default exports are a nuisance when renaming exported elements. The refactoring doesn't work properly since each user can provide his own name.
- [x] Publish new config on NPM
- [x] Use new config here
- [x] Disable TYPESCRIPT_STANDARD linter in [.mega-linter.yml](https://github.com/lars-reimann/api-editor/blob/main/.mega-linter.yml)
